GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: 🚀 Публикуем образ в GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/matrix-variant23
          IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
          docker tag matrix-variant23:latest $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
          docker tag matrix-variant23:latest $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:${{ github.sha }}
          echo "✅ Образ опубликован: $IMAGE_ID:latest"
