name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  Скачиваем код
        uses: actions/checkout@v4
      
      - name:  Устанавливаем компилятор
        run: |
          sudo apt update
          sudo apt install -y gcc make
      
      - name: Запускаем сборку
        run: |
          chmod +x cicd/build.sh
          ./cicd/build.sh
      
      - name:  Сохраняем результат
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: |
            usr/local/bin/matrix
            DEBIAN/
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name:  Скачиваем код
        uses: actions/checkout@v4
      
      - name:  Скачиваем результат сборки
        uses: actions/download-artifact@v4
        with:
          name: build-result
      
      - name:  Запускаем тесты
        run: |
          chmod +x usr/local/bin/matrix
          chmod +x cicd/test.sh
          ./cicd/test.sh
      
      - name: Передаём результат
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: |
            usr/local/bin/matrix
            DEBIAN/
          retention-days: 1

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name:  Скачиваем код
        uses: actions/checkout@v4
      
      - name:  Скачиваем результат тестов
        uses: actions/download-artifact@v4
        with:
          name: test-result
      
      - name: Устанавливаем dpkg
        run: sudo apt install -y dpkg-dev
      
      - name: Собираем deb-пакет
        run: |
          chmod +x cicd/package.sh
          ./cicd/package.sh
      
      - name:  Сохраняем пакет
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: "*.deb"
          retention-days: 7

  deploy:
    needs: package
    runs-on: ubuntu-latest
    
    steps:
      - name:  Скачиваем код
        uses: actions/checkout@v4
      
      - name:  Скачиваем deb-пакет
        uses: actions/download-artifact@v4
        with:
          name: deb-package
      
      - name:  Устанавливаем Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io
      
      - name:  Собираем Docker-образ
        run: docker build -t matrix-variant23:latest .
      
      - name: 🧪 Тестируем Docker-образ
        run: |
          chmod +x cicd/docker-test.sh
          ./cicd/docker-test.sh
      
      - name: Сохраняем Docker-образ
        run: |
          docker save matrix-variant23:latest -o matrix-variant23-image.tar
          gzip matrix-variant23-image.tar
      
      - name:  Загружаем Docker-образ
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: matrix-variant23-image.tar.gz
          retention-days: 7
